apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quarkus-techlab-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
  - binding:
      name: quarkus-techlab-pipelinebinding
    template:
      name: quarkus-techlab-triggertemplate